### ISSUE TITLE
Add bluesky also on second workstation: xf11id-ws2

### ISSUE THREAD

**Issue by MikeHart85** [NSLS2/chx-profile-collection#22]
This was requested in a comment on #16.

Opening issue to make sure this doesn't get lost.

If this wasn't done already, it may be a while before we can get to it, since our time is now tied up in the remote task force work.

**Comment by mrakitin** [comment]
I think it should be closed. The ws2 was already in the list of workstations we push to: https://github.com/NSLS-II/playbooks/blob/a6550e5e29ac361d6844eb06d97eac4ffb69ff26/production#L373. The only thing it was missing was the `/opt/conda/.condarc` configuration file. I copied it from ws1, and we should be good:
```yaml
mrakitin@xf11id-ws2:~$ cat /opt/conda/.condarc
channel_priority: strict
channels:
- https://conda.nsls2.bnl.gov/conda/nsls2-tag
- https://conda.nsls2.bnl.gov/conda/defaults
create_default_packages:
- anaconda-client
- pip
envs_dirs:
- ~/conda_envs
- /opt/conda_envs
ssl_verify: false
show_channel_urls: True
channel_alias: https://conda.nsls2.bnl.gov/conda/
```

I was able to start `bsui` with the latest conda env on that machine.

cc @afluerasu
